spring:
  datasource:
    url: jdbc:mysql://localhost:3306/company?useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 11mysql11
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always


##    hibernate:
##      ddl-auto: create-drop
##    defer-datasource-initialization: true
#
#
##        spring:
##          datasource:
##            url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Europe/Warsaw
##            driver-class-name: com.mysql.cj.jdbc.Driver
##            username: root
##            password: 11mysql11
##          jpa:
##            hibernate:
##              defer-datasource-initialization: true
##              ddl-auto: update